version: "2"
services:
  db:
    container_name: 'database_postgres'
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_storage:/var/lib/postgresql/data
  backend:
    build: ./backend
    ports:
      - "80:80"
    expose:
      - "80:80"
    depends_on:
      db:
        condition: service_started
    links:
      - db
    command: python3 -m uvicorn src.main:app --proxy-headers --host 0.0.0.0 --port 80

volumes:
  pg_storage: Null