"""like_field_deleted

Revision ID: 5cab50560a21
Revises: 19b5d510b8a5
Create Date: 2023-01-18 18:40:14.135133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cab50560a21'
down_revision = '19b5d510b8a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'likes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
