"""likes_many_2_many_fix

Revision ID: db6da5f3dc11
Revises: 1b00e6ab80c6
Create Date: 2023-01-18 19:50:31.999733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db6da5f3dc11'
down_revision = '1b00e6ab80c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
